Add required event fields
GoodNightCouchSide/gncs-api pull request #25
Opened 2023-01-20 00:17 UTC by tkdamian

### Description
Add the missing required fields to create and update  the event
- Headliner <String>
- Support <String(format: Array<String>)>
- Date: Date Iso

### Type of change
- [] Bug fix
- [x] New feature
- [ ] Documentation Update
- [x] Increase/Reduce Tests
- [ ] Dev Tool Implementation

### Checklist
- [x] Tests are written
- [ ] The new feature is documented

### Screenshots
  

### Related Issues or Pull Requests
[NOTE]: # ( Be sure to use "Fixes #123" or "Closes #42" to close any related issues. )

2023-01-21 00:23 UTC, tkdamian commented on tests/functional/event.spec.ts
> +        assert.equal(response.body().event[key].slice(0, 23), requestBody[key])
ich glaube das ist ein bug im container. ich habe auch versucht ein datum mit zeitzone +1 anzulegen und zurück habe ich das gleiche datum aber mit zeitzone 0 bekommen

2023-01-23 08:54 UTC, hulkoba commented on tests/functional/event.spec.ts
> +        assert.equal(response.body().event[key].slice(0, 23), requestBody[key])
Machst du ein (Bug)Ticket daraus?

2023-01-23 08:56 UTC, hulkoba requested changes

2023-01-23 08:56 UTC, hulkoba commented on app/Models/Event.ts
> +  public support?: string
Ohne '?' :)

2023-01-23 08:56 UTC, hulkoba commented on app/Models/Event.ts
> +  public date: DateTime
Wir hatten gesagt wir trennen Tag und Uhrzeit? https://github.com/GoodNightCouchSide/gncs-api/issues/20

2023-01-24 08:08 UTC, hulkoba approved these changes

2023-01-24 09:55 UTC, merged

2023-01-24 10:04 UTC, tkdamian commented
Closes #20